name: CI

on:
  push:
    branches:
      - master
jobs:
  myjob:
    runs-on: self-hosted # linux required if you want to use docker
    steps:  
    - uses: actions/checkout@v2
    # Those steps are executed directly on the VM
    - run: bazel build ...